name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+(-.+)?'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:

  check-code:
    name: Check quality
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check code
      run: |
        pre-commit install
        pre-commit run -a

  run-test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/checkout@v2
    - run: pip install -r requirements.txt
    - run: pytest -vv .
